name: EAS Android Build (APK)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Login to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami || eas login --token "$EXPO_TOKEN"

      - name: Build Android APK (preview profile)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile preview --non-interactive

      - name: Output build URL
        run: |
          echo "Visit your builds: https://expo.dev/accounts/_/projects/kamchatka/builds"

