name: EAS Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: EAS login
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami

      - name: Build (production)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform all --profile production --non-interactive

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eas-build-artifacts
          path: |
            dist/*.apk
            dist/*.aab
            dist/*.ipa