version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: kamchatour_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kamchatour2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: kamchatour_hub
      DB_USER: postgres
      DB_PASSWORD: kamchatour2024
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: kamchatour-super-secret-key-2024
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: