openapi: 3.0.0
info:
  title: Kamchatour Hub API Gateway
  version: 0.1.0
paths:
  /api/health:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${YC_FN_HEALTH_ID}
        tag: "$latest"
      responses:
        '200': { description: OK }
  /api/env:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${YC_FN_ENV_ID}
        tag: "$latest"
      responses:
        '200': { description: OK }
  /api/tg/send:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${YC_FN_TG_SEND_ID}
        tag: "$latest"
      responses:
        '200': { description: OK }
  /api/tg/webhook:
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${YC_FN_TG_WEBHOOK_ID}
        tag: "$latest"
      responses:
        '200': { description: OK }

