name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Expo doctor
        run: npx --yes expo-doctor

      - name: Lint
        run: npx eslint . --ext .js,.jsx

      - name: Test
        run: npm test -- --ci --reporters=default

      - name: Build web
        run: npm run build
