name: Vercel Env Dump

on:
  workflow_dispatch:
    inputs:
      vercel_org_id:
        description: Vercel team/org slug or ID (e.g., pospks-projects)
        required: true
        default: pospks-projects
      vercel_project_id:
        description: Vercel project ID (e.g., prj_7IsGks2Kk8TfpfFMQFxgqf86vePk)
        required: true
        default: prj_7IsGks2Kk8TfpfFMQFxgqf86vePk

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Dump env (production)
        id: prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          ORG: ${{ inputs.vercel_org_id }}
          PROJECT: ${{ inputs.vercel_project_id }}
        run: |
          vercel env ls --project "$PROJECT" --environment production --token "$VERCEL_TOKEN" --scope "$ORG" | tee prod.txt | cat

      - name: Dump env (preview)
        id: prev
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          ORG: ${{ inputs.vercel_org_id }}
          PROJECT: ${{ inputs.vercel_project_id }}
        run: |
          vercel env ls --project "$PROJECT" --environment preview --token "$VERCEL_TOKEN" --scope "$ORG" | tee preview.txt | cat

      - name: Dump env (development)
        id: dev
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          ORG: ${{ inputs.vercel_org_id }}
          PROJECT: ${{ inputs.vercel_project_id }}
        run: |
          vercel env ls --project "$PROJECT" --environment development --token "$VERCEL_TOKEN" --scope "$ORG" | tee development.txt | cat

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vercel-envs
          path: |
            prod.txt
            preview.txt
            development.txt
