name: Vercel Env Dump

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify secrets
        run: |
          if [ -z "${VERCEL_TOKEN}" ] || [ -z "${VERCEL_ORG_ID}" ] || [ -z "${VERCEL_PROJECT_ID}" ]; then
            echo "::error::Missing Vercel secrets. Set VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID in repo/team secrets."; exit 1; fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Dump production env
        run: vercel env ls --project "$VERCEL_PROJECT_ID" --environment production --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID" | tee vercel-env-production.txt

      - name: Dump preview env
        run: vercel env ls --project "$VERCEL_PROJECT_ID" --environment preview --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID" | tee vercel-env-preview.txt

      - name: Dump development env
        run: vercel env ls --project "$VERCEL_PROJECT_ID" --environment development --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID" | tee vercel-env-development.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vercel-env-dump
          path: |
            vercel-env-production.txt
            vercel-env-preview.txt
            vercel-env-development.txt
          retention-days: 7

